<template>
  <a-card style="margin: 20px">
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
    <div>sssss</div>
  </a-card>
</template>

<script lang="ts" setup name=""></script>

<style scoped></style>
